// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAElcjp2yI2ypi1TUmjFd5JeR8fR8zRbhc',
    appId: '1:577400848756:web:dd7c46b90865020de16c21',
    messagingSenderId: '577400848756',
    projectId: 'matget-2510',
    authDomain: 'matget-2510.firebaseapp.com',
    storageBucket: 'matget-2510.firebasestorage.app',
    measurementId: 'G-RM1KFDPJ5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcg92KW89hz3WJ4b7dGk0W00fLrWVc2NQ',
    appId: '1:577400848756:android:c6f11f9bc3e90005e16c21',
    messagingSenderId: '577400848756',
    projectId: 'matget-2510',
    storageBucket: 'matget-2510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJGhzwf5AjP5zZerVAqa_JGpvY-12Alc',
    appId: '1:577400848756:ios:2fb442b8c9aa64a9e16c21',
    messagingSenderId: '577400848756',
    projectId: 'matget-2510',
    storageBucket: 'matget-2510.firebasestorage.app',
    iosBundleId: 'com.example.matget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeJGhzwf5AjP5zZerVAqa_JGpvY-12Alc',
    appId: '1:577400848756:ios:2fb442b8c9aa64a9e16c21',
    messagingSenderId: '577400848756',
    projectId: 'matget-2510',
    storageBucket: 'matget-2510.firebasestorage.app',
    iosBundleId: 'com.example.matget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAElcjp2yI2ypi1TUmjFd5JeR8fR8zRbhc',
    appId: '1:577400848756:web:b59c46e19b06e121e16c21',
    messagingSenderId: '577400848756',
    projectId: 'matget-2510',
    authDomain: 'matget-2510.firebaseapp.com',
    storageBucket: 'matget-2510.firebasestorage.app',
    measurementId: 'G-997QN1SHY2',
  );
}
